DROP TABLE IF EXISTS ORDERS;
CREATE TABLE IF NOT EXISTS ORDERS(ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, ORDER_NAME VARCHAR(100),
    DATESTARTCOOKING VARCHAR(100), TIMECOOKING VARCHAR(100), ORDERDONE VARCHAR(100));
--DATESTARTCOOKING TIMESTAMP